### ISSUE TITLE
Cannot delete states

### ISSUE THREAD

**Issue by Swiftnesses** [SergeRegoor/nl.regoor.statecontrol#4]
I believe this is only present before they've been used in a flow?

Try creating a new tab, and adding new states, then deleting them.

**Comment by SergeRegoor** [comment]
Just did, and no problems deleting a state.
Is it possible the state was applied to a section, or you used a state in a follow-up?
In that case, you should get a message that the state is in use. Could that be the case, or did you receive an error message?

**Comment by Swiftnesses** [comment]
I need to check, no error, but the console said something about the id being null.

**Comment by SergeRegoor** [comment]
Fixed in v0.2.1.
