### ISSUE TITLE
Settings could not be loaded

### ISSUE THREAD

**Issue by Radiotechniman** [SergeRegoor/nl.regoor.statecontrol#6]
OS 0.10.7
When clicking the app in the settings page the following popup shows:
"Settings could not be loaded, sorry Please try again"

**Comment by SergeRegoor** [comment]
Thank you for reporting the issue. The bug was fixed in the source code yesterday, and I'm awaiting approval for the app update. I'll close this issue once the update has been published.

**Comment by Radiotechniman** [comment]
awesome :-)
